// types for fetching posts by category 
export const FETCH_IMAGES_BY_CATEGORY_REQUEST = "FETCH_IMAGES_BY_CATEGORY_REQUEST";
export const FETCH_IMAGES_BY_CATEGORY_SUCCESS = "FETCH_IMAGES_BY_CATEGORY_SUCCESS";
export const FETCH_IMAGES_BY_CATEGORY_FAILURE = "FETCH_IMAGES_BY_CATEGORY_FAILURE";
export const NO_SUCH_ID_FOUND = "NO_SUCH_ID_FOUND";

//types for fetching posts by page 
export const FETCH_IMAGES_BY_PAGES_REQUEST = "FETCH_IMAGES_BY_PAGES_REQUEST";
export const FETCH_IMAGES_BY_PAGES_SUCCESS = "FETCH_IMAGES_BY_PAGES_SUCCESS";
export const FETCH_IMAGES_BY_PAGES_FAILURE = "FETCH_IMAGES_BY_PAGES_FAILURE";
