export const FETCH_CAT_CATEGORIES_REQUEST = "FETCH_CAT_CATEGORIES_REQUEST";
export const FETCH_CAT_CATEGORIES_SUCCESS = "FETCH_CAT_CATEGORIES_SUCCESS";
export const FETCH_CAT_CATEGORIES_FAILURE = "FETCH_CAT_CATEGORIES_FAILURE";